4.20.1-pt1.10.2-synapse1.4.1:
  extra_tags:
    - "4.20.1"
    - latest
  template:
    template_path: templates/Dockerfile.hpu
    base_image: public.ecr.aws/habanalabs/pytorch-installer:1.10.2-ubuntu18.04-1.4.1-latest
    pip_dependencies:
      - tensorboard
      - transformers[sklearn,sentencepiece,audio,vision]==4.20.1
      - datasets==2.3.2
      - optimum[habana]