name: base
channels:
- conda-forge
dependencies:
- python=3.9.13
- nvidia::cudatoolkit=11.5
- pytorch::pytorch=1.11.0=py3.9_cuda11.5_cudnn8.3.2_0
- tensorboard
- mpi4py=3.0
- pip:
  - transformers[sklearn,sentencepiece,audio,vision]==4.20.1
