name: base
channels:
- conda-forge
dependencies:
- python=3.9.13
- nvidia::cudatoolkit=11.6
- pytorch::pytorch=1.13.0=py3.9_cuda11.6*
- tensorboard
- mpi4py=3.0
- jupyter
- pip:
  - transformers[sklearn,sentencepiece,audio,vision]==4.24.0
  - datasets==2.3.2
