1.3.0-ort1.11-cuda11.5:
  extra_tags:
    - "1.3.0-cuda"
    - latest-cuda
  template:
    template_path: templates/Dockerfile.gpu
    base_image: nvidia/cuda:11.5.1-base-ubuntu20.04
    env_variables:
      - key: TEST
        value: 1
    conda_channels:
      - conda-forge
    conda_dependencies:
      - python=3.9.13
      - nvidia::cudatoolkit=11.5
      - pytorch::pytorch=1.11.0=py3.9_cuda11.5_cudnn8.3.2_0
      - pip:
        - optimum[onnxruntime-gpu]==1.3.0
        - datasets==2.3.2

1.3.0-ort1.11-cpu:
  extra_tags:
    - "1.3.0-cpu"
    - latest-cpu
  template:
    template_path: templates/Dockerfile.cpu
    base_image: ubuntu:20.04
    env_variables:
      - key: TEST
        value: 1
    conda_channels:
      - conda-forge
    conda_dependencies:
      - python=3.9.13
      - pytorch::pytorch=1.11.0=py3.9_cpu_0
      - tensorboard
      - pip:
        - optimum[onnxruntime]==1.3.0
        - datasets==2.3.2

