4.24.0-pt1.13-cuda11.6:
  extra_tags:
    - "4.24.0-pt-cuda"
    - latest-pt-cuda
  template:
    template_path: templates/Dockerfile.gpu
    base_image: nvidia/cuda:11.6.1-base-ubuntu20.04
    env_variables:
      - key: TEST
        value: 1
    conda_channels:
      - conda-forge
    conda_dependencies:
      - python=3.9.13
      - nvidia::cudatoolkit=11.6
      - pytorch::pytorch=1.13.0=py3.9_cuda11.6*
      - tensorboard
      - mpi4py=3.0 # installs cuda-aware openmpi
      - jupyter 
      - pip:
        - transformers[sklearn,sentencepiece,audio,vision]==4.24.0
        - datasets==2.3.2

4.24.0-pt1.13-cpu:
  extra_tags:
    - "4.24.0-pt-cpu"
    - latest-pt-cpu
  template:
    template_path: templates/Dockerfile.cpu
    base_image: ubuntu:20.04
    env_variables:
      - key: TEST
        value: 1
    conda_channels:
      - conda-forge
    conda_dependencies:
      - python=3.9.13
      - pytorch::pytorch=1.13.0=py3.9_cpu_0
      - tensorboard
      - jupyter 
      - pip:
        - transformers[sklearn,sentencepiece,audio,vision]==4.24.0
        - datasets==2.3.2


########################### TENSORFLOW ###########################

4.24.0-tf2.9-cuda11.2:
  extra_tags:
    - "4.24.0-tf-cuda"
    - latest-tf-cuda
  template:
    template_path: templates/Dockerfile.gpu
    base_image: nvidia/cuda:11.2.2-base-ubuntu20.04
    env_variables:
      - key: CONDA_OVERRIDE_CUDA
        value: "11.2"
    conda_channels:
      - conda-forge
    conda_dependencies:
      - python=3.9.13
      - nvidia::cudatoolkit=11.2
      - tensorflow=2.9.1=*cuda112*py39*
      - tensorboard
      - jupyter 
      - pip:
        - transformers[sklearn,sentencepiece,audio,vision]==4.24.0
        # - tensorflow-text # not compatible

4.24.0-tf2.9-cpu:
  extra_tags:
    - "4.24.0-cpu"
    - latest-cpu
  template:
    template_path: templates/Dockerfile.cpu
    base_image: ubuntu:20.04
    env_variables:
      - key: TEST
        value: 1
    conda_channels:
      - conda-forge
    conda_dependencies:
      - python=3.9.13
      - tensorflow=2.9.1=*cpu*py39*
      - tensorboard
      - jupyter 
      - pip:
        - transformers[sklearn,sentencepiece,audio,vision]==4.24.0
        # - tensorflow-text # not compatible

