4.20.1-pt1.11-cuda11.5-deepspeed-training:
  extra_tags:
    - "4.20.1-deepspeed-training"
    - latest-deepspeed-training
  template:
    template_path: templates/Dockerfile.cpu
    base_image: nvidia/cuda:11.3.1-base-ubuntu20.04
    env_variables:
      - key: DS_BUILD_CPU_ADAM
        value: 1
      - key: DS_BUILD_AIO
        value: 1
      - key: DS_BUILD_UTILS
        value: 1
    conda_channels:
      - conda-forge
    conda_dependencies:
      - python=3.9.13
      - nvidia::cudatoolkit=11.3
      - pytorch::pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
      - tensorboard
      - mpi4py=3.0 # installs cuda-aware openmpi
      - pip:
        - transformers[sklearn,sentencepiece,audio,vision]==4.20.1
        - datasets==2.3.2
        - deepspeed --global-option="build_ext" --global-option="-j8" --no-cache -v --disable-pip-version-check

4.20.1-pt1.11-cuda11.5-deepspeed-inference:
  extra_tags:
    - "4.20.1-deepspeed-inference"
    - latest-deepspeed-inference
  template:
    template_path: templates/Dockerfile.cpu
    base_image: nvidia/cuda:11.3.1-base-ubuntu20.04
    env_variables:
      - key: DS_BUILD_TRANSFORMER_INFERENCE
        value: 1
    conda_channels:
      - conda-forge
    conda_dependencies:
      - python=3.9.13
      - nvidia::cudatoolkit=11.3
      - pytorch::pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
      - mpi4py=3.0 # installs cuda-aware openmpi
      - pip:
        - transformers[sentencepiece]==4.20.1
        - datasets==2.3.2
        - deepspeed --global-option="build_ext" --global-option="-j8" --no-cache -v --disable-pip-version-check