name: base
channels:
- conda-forge
dependencies:
- python=3.9.13
- pytorch::pytorch=1.11.0=py3.9_cpu_0
- tensorboard
- jupyter
- pip:
  - transformers[sklearn,sentencepiece,audio,vision]==4.23.0
  - datasets==2.3.2
