name: optimum/onnxruntime/1.2.3/ort1.11/cuda11.5

on:
  push:
    branches:
    - master
    paths:
    - optimum/onnxruntime/1.2.3/ort1.11/cuda11.5/*
    - .github/workflows/optimum-onnxruntime-1.2.3-ort1.11-cuda11.5.yml
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: 'public'

    - id: installs
      name: install dependencies
      run: |
        pip install -r requirements.txt

    - id: build
      name: build docker image
      run: |
        docker build -t public.ecr.aws/t6m7g5n4/optimum-onnxruntime:1.2.3-cuda -t public.ecr.aws/t6m7g5n4/optimum-onnxruntime:latest-cuda -t public.ecr.aws/t6m7g5n4/optimum-onnxruntime:1.2.3-ort1.11-cuda11.5 -f optimum/onnxruntime/1.2.3/ort1.11/cuda11.5/Dockerfile optimum/onnxruntime/1.2.3/ort1.11/cuda11.5
    
    - id: scan
      name: run security scans
      run: |
        echo "docker scan"
    
    - id: test
      name: run tests
      run: |
        pytest -q -s --tag public.ecr.aws/t6m7g5n4/optimum-onnxruntime:1.2.3-ort1.11-cuda11.5 tests/test_docker_run.py

    - id: push
      name: push image to registry
      run: |
        docker push --all-tags public.ecr.aws/t6m7g5n4/optimum-onnxruntime


    # - uses: docker/build-push-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     tags: public.ecr.aws/t6m7g5n4/optimum-onnxruntime:1.2.3-cuda,public.ecr.aws/t6m7g5n4/optimum-onnxruntime:latest-cuda,public.ecr.aws/t6m7g5n4/optimum-onnxruntime:1.2.3-ort1.11-cuda11.5
    #     path: optimum/onnxruntime/1.2.3/ort1.11/cuda11.5