name: containers/transformers/training/4.21.2/tf2.9/cuda11.2

on:
  push:
    branches:
    - main
    paths:
    - containers/transformers/training/4.21.2/tf2.9/cuda11.2/*
    - .github/workflows/transformers-training-4.21.2-tf2.9-cuda11.2.yml
  pull_request:
    branches:
    - main
    paths:
    - containers/transformers/training/4.21.2/tf2.9/cuda11.2/*
    - .github/workflows/transformers-training-4.21.2-tf2.9-cuda11.2.yml
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - id: login 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - id: installs
      name: install dependencies
      run: |
        pip install -r requirements.txt

    - id: build
      name: build docker image
      run: |
        docker build -t huggingface/transformers-training:4.21.2-tf-cuda -t huggingface/transformers-training:latest-tf-cuda -t huggingface/transformers-training:4.21.2-tf2.9-cuda11.2 -f containers/transformers/training/4.21.2/tf2.9/cuda11.2/Dockerfile containers/transformers/training/4.21.2/tf2.9/cuda11.2
    
    - id: scan
      name: run security scans
      run: |
        echo "docker scan"
    
    - id: test
      name: run tests
      run: |
        pytest -q -s --tag huggingface/transformers-training:4.21.2-tf2.9-cuda11.2 tests/test_docker_run.py

    - id: push
      name: push image to registry
      if: github.event_name == 'push'
      run: |
        docker push --all-tags huggingface/transformers-training