name: containers/transformers/deepspeed/4.20.1/pt1.11/cuda11.3/training

on:
  push:
    branches:
    - main
    paths:
    - containers/transformers/deepspeed/4.20.1/pt1.11/cuda11.3/training/*
    - .github/workflows/transformers-deepspeed-4.20.1-pt1.11-cuda11.3-training.yml
  pull_request:
    branches:
    - main
    paths:
    - containers/transformers/deepspeed/4.20.1/pt1.11/cuda11.3/training/*
    - .github/workflows/transformers-deepspeed-4.20.1-pt1.11-cuda11.3-training.yml
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - id: login 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - id: installs
      name: install dependencies
      run: |
        pip install -r requirements.txt

    - id: build
      name: build docker image
      run: |
        docker build -t huggingface/transformers-deepspeed:4.20.1-training -t huggingface/transformers-deepspeed:latest-training -t huggingface/transformers-deepspeed:4.20.1-pt1.11-cuda11.3-training -f containers/transformers/deepspeed/4.20.1/pt1.11/cuda11.3/training/Dockerfile containers/transformers/deepspeed/4.20.1/pt1.11/cuda11.3/training
    
    - id: scan
      name: run security scans
      run: |
        echo "docker scan"
    
    - id: test
      name: run tests
      run: |
        pytest -q -s --tag huggingface/transformers-deepspeed:4.20.1-pt1.11-cuda11.3-training tests/test_docker_run.py

    - id: push
      name: push image to registry
      if: github.event_name == 'push'
      run: |
        docker push --all-tags huggingface/transformers-deepspeed