name: containers/transformers/inference/4.25.1/pt1.13/cpu

on:
  push:
    branches:
    - main
    paths:
    - containers/transformers/inference/4.25.1/pt1.13/cpu/*
    - .github/workflows/transformers-inference-4.25.1-pt1.13-cpu.yml
  pull_request:
    branches:
    - main
    paths:
    - containers/transformers/inference/4.25.1/pt1.13/cpu/*
    - .github/workflows/transformers-inference-4.25.1-pt1.13-cpu.yml
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - id: login 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - id: installs
      name: install dependencies
      run: |
        pip install -r requirements.txt

    - id: build
      name: build docker image
      run: |
        docker build -t huggingface/transformers-inference:4.25.1-cpu -t huggingface/transformers-inference:latest-cpu -t huggingface/transformers-inference:4.25.1-pt1.13-cpu -f containers/transformers/inference/4.25.1/pt1.13/cpu/Dockerfile containers/transformers/inference/4.25.1/pt1.13/cpu
    
    - id: scan
      name: run security scans
      run: |
        echo "docker scan"
    
    - id: test
      name: run tests
      run: |
        pytest -q -s --tag huggingface/transformers-inference:4.25.1-pt1.13-cpu tests/test_docker_run.py

    - id: push
      name: push image to registry
      if: github.event_name == 'push'
      run: |
        docker push --all-tags huggingface/transformers-inference