name: Publish phischmi/pytorch:4.20.1-pt1.11-cpu

on:
  push:
    branches:
    - master
    paths:
    - transformers/training/4.20.1/pt1.11/cpu/*
    - .github/workflows/transformers-training-4.20.1-pt1.11-cpu.yml
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - id: installs
      run: |
        pip install -r requirements.txt

    - id: build
      run: |
        docker build -t 4.20.1,latest,4.20.1-pt1.11-cpu -f transformers/training/4.20.1/pt1.11/cpu/Dockerfile transformers/training/4.20.1/pt1.11/cpu
    
    - id: scan
      run: |
        echo "docker scan"
    
    - id: test
      run: |
        pytest -q -s --tag 4.20.1-pt1.11-cpu tests/test_docker_run.py

    - id: push
      run: |
        echo "push"

    # - uses: docker/build-push-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     repository: phischmi/pytorch
    #     tags: 4.20.1,latest,4.20.1-pt1.11-cpu
    #     path: transformers/training/4.20.1/pt1.11/cpu